version: '3.9'

services:
  db:
    image: postgres:15
    container_name: nestjs_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_ENABLE_CSRF: "False"
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db-data: {}
