version: '3'
services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432  # make sure you don't have another container running on 5432

    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=ironman
      - POSTGRES_PASSWORD=ironman

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080